-- select within select(sec 4): problem 5
-- select within select(sec 4): problem 7
-- select within select(sec 4): problem 9
-- join (sec 6): problem 11
-- join (sec 6): problem 13
-- more join (sec 7): problem 12
-- more join (sec 7): problem 13
-- more join (sec 7): problem 14
-- self join (sec 9): problem 9
-- self join (sec 9): problem 10